In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
# Importing the dataset
dataset = pd.read_csv('F:/sem_5/tarp/p.csv')
X = dataset.iloc[:, 0:13].values
y = dataset.iloc[:,-1].values

In [15]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [16]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [17]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)


GaussianNB(priors=None)

In [18]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [19]:
print(cm)

[[26  0  0  1 13]
 [ 2  1  1  0  6]
 [ 0  2  0  0  7]
 [ 0  0  1  1 10]
 [ 0  0  0  1  4]]


In [20]:
print(y_pred)

[0 4 1 0 0 1 3 0 4 4 4 4 0 0 4 4 0 4 0 4 4 2 0 4 0 4 4 4 4 4 4 0 4 2 4 0 0
 0 4 1 4 4 0 4 0 3 0 4 4 4 0 4 4 4 0 4 0 0 4 4 4 0 4 4 3 0 4 4 4 0 0 4 4 0
 0 0]
